services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
  mysql-data:
